// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCREs5m5x2H5AZvvGEwbVlE8uWGU0zY8Dg',
    appId: '1:678733943298:web:7712ec60f2024a81628d1b',
    messagingSenderId: '678733943298',
    projectId: 'ultimate-calculator-20b8c',
    authDomain: 'ultimate-calculator-20b8c.firebaseapp.com',
    databaseURL: 'https://ultimate-calculator-20b8c-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-calculator-20b8c.appspot.com',
    measurementId: 'G-5VYYP1JFCW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPR92hKL_p8KkccP1zTVGcXt3pYOm-Yh0',
    appId: '1:678733943298:android:011541ac94e09087628d1b',
    messagingSenderId: '678733943298',
    projectId: 'ultimate-calculator-20b8c',
    databaseURL: 'https://ultimate-calculator-20b8c-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-calculator-20b8c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBItctK0RL_ttjTQMowvjxH_kFaitVn3IE',
    appId: '1:678733943298:ios:747afb6a9e206637628d1b',
    messagingSenderId: '678733943298',
    projectId: 'ultimate-calculator-20b8c',
    databaseURL: 'https://ultimate-calculator-20b8c-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-calculator-20b8c.appspot.com',
    iosClientId: '678733943298-s5vhh4p2epir8j6rsfuhv9lomu7sni1k.apps.googleusercontent.com',
    iosBundleId: 'com.ultimatecalculator.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBItctK0RL_ttjTQMowvjxH_kFaitVn3IE',
    appId: '1:678733943298:ios:e315b9929adc7447628d1b',
    messagingSenderId: '678733943298',
    projectId: 'ultimate-calculator-20b8c',
    databaseURL: 'https://ultimate-calculator-20b8c-default-rtdb.firebaseio.com',
    storageBucket: 'ultimate-calculator-20b8c.appspot.com',
    iosClientId: '678733943298-gbuo5l1q96c09trkcvamrhd9odijm4l9.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
